# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TabMemo-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TabMemo-Swift
  pod 'TagListView', '~> 1.0'
  pod 'EZAlertController', '3.2'
  pod ‘RealmSwift’

  target 'TabMemo-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabMemo-SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
